### PR TITLE
Adds an arm build to the earthly build workflow

### LINKED ISSUE #171: Build and push arm64 Docker images
This will make it easier to develop on Apple Silicon Macs and on NVIDIA Jetson edge compute devices.

### PR DESCRIPTION
**Pull request by dsobek**
Adds an arm64 build to Earthfile and configures the earthly-build workflow to build for linux/arm64 and linux/amd64 platforms following https://docs.earthly.dev/docs/guides/multi-platform.

Tested by building all platforms locally on a linux/arm64 machine.

~~Creates an arm64 build using a macos github runner.~~

resolves #171

### CODE REVIEW

**Review by EzraBrooks — CHANGES_REQUESTED** [review]
Using Qemu will take a literal eternity since it emulates every CPU instruction - I recommend instead changing the space-ros-image job into a matrix job that runs on ubuntu x86 and ubuntu arm64 in parallel instead

**Comment by EzraBrooks** [comment]
@dsobek and I discovered that for some reason the ubuntu arm64 runners cannot be referenced directly without a custom runner configuration, so we're going to have to use the apple silicon Mac runners with docker to build linux images

**Comment by asimonov** [comment]
looks like it is running on both amd64 and arm64/mac runners?

but for macos you probably need to install docker too.

but in general - what would happen with these 2 images after they are built on 2 runners? will you try to combine into a multi-architecture image? or push as 2 separate images?

**Comment by EzraBrooks** [comment]
>  will you try to combine into a multi-architecture image? or push as 2 separate images?

I don't think @dsobek has gotten this far yet, but it's my understanding that there just needs to be a follow-up job that runs after these two complete that combines their Docker manifest into one multi-platform image. Unsure if Earthly has a helper for that - on my project we do it directly with the Docker CLI.

**Comment by dsobek** [comment]
Thanks for the tip! Sorry I've been hyper-focused on another task recently. I hope to get back to working on this today.

**Comment by dsobek** [comment]
@EzraBrooks I think we should try to use Qemu and see how long it takes. Looks like the M1 runner just doesn't support containerization due to it not supporting the Hypervisor framework. 
https://github.com/abiosoft/colima/issues/1023
https://github.com/orgs/community/discussions/69211

Otherwise can we use large runners or third party runners with this repo?

**Comment by asimonov** [comment]
i am not sure why there is a problem. 

i can build arm64 images on my M1 mac with just vanilla docker and earthly.

not sure if vanilla docker's underlying linux VM requires hypervisor framework... but it would be strange for github to provide macos runners without ability to run docker on them...

with Colima things are more interesting. i can use it as underlying docker linux VM and arm64 build works, just like with vanilla docker. 
but amd64 build is failing. now it is down to sequential executor of colcon with -j1, so it should be using 1 core. and 12gb of RAM. and it still fails with seg violation kills.
amd64 build on colima requires hypervisor framework. but as I say we do not need colima for arm64 builds.

**Review by EzraBrooks — COMMENTED** [review]
I told you qemu would be slow ;)

**Pull request closed without merging**
