### PR TITLE
Roll back the 'launch' repo version to avoid a breakage when building…

### PR DESCRIPTION
**Pull request by mjeronimo**
… MoveIt2 against Space ROS.

Signed-off-by: Michael Jeronimo <michael.jeronimo@openrobotics.org>

### CODE REVIEW

**Review by shonigmann — APPROVED** [review]
looks good to me. Lets just remember to re-target master when https://github.com/ros2/launch/issues/588 is closed

**Comment by mjeronimo** [comment]
@shonigmann I was going to add an issue as a reminder, but it seems I don't have permission to. Can you add me?

**Comment by shonigmann** [comment]
very strange... you're a member of the `developers` group, which has `maintainer` permissions set. You should be able to manage issues...

**Comment by mjeronimo** [comment]
I'm not seeing an issues tab on the space-ros repo page.

**Comment by shonigmann** [comment]
In the end, it was because this repo is a fork of ros2/ros2. Issues are disabled by default, in favor of the parent repo. I have just enabled them.

**Comment by mjeronimo** [comment]
Added an issue as a reminder: https://github.com/space-ros/space-ros/issues/2

**Pull request merged**
